In [6]:
import numpy as np
from numpy.linalg import inv
def Bet_Estimator(X,Y):
    XT = np.transpose(X)
    XTX = np.matmul(XT, X)
    Betas = np.matmul(np.matmul(inv(XTX),XT),Y)
    return(Betas)

X = np.array([[1,0],
              [0,1],
              [1,1],
              [1,1]])
Y = np.array([[2],
              [3],
              [4],
              [4]])
Bet_Estimator(X,Y)

array([[1.6],
       [2.6]])

In [7]:
errors = [0.1, .5, -.4, .1, -.3, .2]
p = 2
n = len(errors)
RSS = 0
for error in errors:
    RSS = RSS + error**2 
variance =RSS/(n-p)
print('RSS: ' + str(RSS))
print('Variance: ' + str(variance))

RSS: 0.56
Variance: 0.14


In [5]:
import numpy as np
from numpy.linalg import inv

# Define values needed
X = np.array([[1,0],
              [0,1],
              [1,1],
              [1,1]])
XT = np.transpose(X)
x_new = np.array([[1],
                  [1]])
x_newT = np.transpose(x_new)
XTXinv = inv(np.matmul(XT, X))

value = 1 + np.matmul(np.matmul(x_newT, XTXinv),x_new)
value

array([[1.4]])

In [4]:
np.matmul(np.matmul(x_newT, XTXinv),x_new)

array([[0.4]])

In [14]:
4/3

1.3333333333333333